# see https://getantidote.github.io/install

# ANTIDOTE_DIR=${TOOLS_DIR}/zsh-antidote
ANTIDOTE_DIR=/opt/tools/zsh-antidote

# Set the name of the static .zsh plugins file antidote will generate.
# zsh_plugins=${ZDOTDIR:-~}/.zsh_plugins.zsh
zsh_plugins=${ANTIDOTE_DIR}/etc/plugins.zsh

# Ensure you have a plugins.txt file where you can add plugins.
[[ -f ${zsh_plugins:r}.txt ]] || touch ${zsh_plugins:r}.txt

# Lazy-load antidote.
# fpath+=(${ZDOTDIR:-~}/.antidote)
# autoload -Uz $fpath[-1]/antidote

fpath+=(${ANTIDOTE_DIR}/bin/)
autoload -Uz ${ANTIDOTE_DIR}/bin/antidote

# Generate static file in a subshell when .zsh_plugins.txt is updated.
if [[ ! $zsh_plugins -nt ${zsh_plugins:r}.txt ]]; then
  (antidote bundle <${zsh_plugins:r}.txt >|$zsh_plugins)
fi

# Source your static plugins file.
source $zsh_plugins


# https://github.com/MichaelAquilina/zsh-auto-notify
export AUTO_NOTIFY_THRESHOLD=5
export AUTO_NOTIFY_EXPIRE_TIME=10000
export AUTO_NOTIFY_TITLE="Hey! %command has just finished"
export AUTO_NOTIFY_BODY="It completed in %elapsed seconds with exit code %exit_code"

# redefine what is ignored by auto-notify
export AUTO_NOTIFY_IGNORE=("docker" "man" "sleep")
# AUTO_NOTIFY_IGNORE+=("docker")
