

# export ANSIBLE_HOME="$HOME/.config/ansible"
export ANSIBLE_HOME="/opt/tools/ansible/var/home"


# https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#control-node-requirements
# eval $(register-python-argcomplete ansible)
# eval $(register-python-argcomplete ansible-config)
# eval $(register-python-argcomplete ansible-console)
# eval $(register-python-argcomplete ansible-doc)
# eval $(register-python-argcomplete ansible-galaxy)
# eval $(register-python-argcomplete ansible-inventory)
# eval $(register-python-argcomplete ansible-playbook)
# eval $(register-python-argcomplete ansible-pull)
# eval $(register-python-argcomplete ansible-vault)