# rust
export CARGO_HOME=/opt/tools/rust
export RUSTUP_HOME=/opt/tools/rust/rustup

# ensure add directories to PATH once
# export PATH="$CARGO_HOME/bin:$PATH"

if ! [[ "$PATH" =~ "$CARGO_HOME/bin" ]]; then
    export PATH="$CARGO_HOME/bin:$PATH"
fi
