
# export NVM_DIR=~/.config/nvm  # no quotes, otherwise breaks

export NVM_DIR=/opt/tools/nvm/var/repo  # no quotes, otherwise breaks

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
