[default]
LOG_FILE = '/opt/tools/pgadmin/var/log/pgadmin4.log'
SQLITE_PATH = '/opt/tools/pgadmin/var/db/pgadmin4.db'
SESSION_DB_PATH = '/opt/tools/pgadmin/var/sessions'
STORAGE_DIR = '/opt/tools/pgadmin/var/storage'
AZURE_CREDENTIAL_CACHE_DIR = '/opt/tools/pgadmin/var/cache/azurecredential'
KERBEROS_CACHE_DIR = '/opt/tools/pgadmin/var/cache/kerberos'

MASTER_PASSWORD = '1234567'
# MASTER_PASSWORD = "{env[PG_PASSWORD]}"
