# This is a comment.

# Add bin-dir to PATH
command -v oh-my-posh >/dev/null || export PATH="$BASE_DIR/bin:$PATH"

# function Set-EnvName {
#     # we assume in-project-venv, e.g. .../projects/<project-name>/.venv
#     # so VIRTUAL_ENV is always ".venv", which is not unique.
#     # so let's use the project-name as ENV_NAME in our wvh-posh-theme.
#     # see https://ohmyposh.dev/docs/configuration/templates
#     if ($env:VIRTUAL_ENV) {
#         $env:ENV_NAME = (get-item $env:VIRTUAL_ENV).parent.name
#     }
# }
# New-Alias -Name 'Set-PoshContext' -Value 'Set-EnvName' -Scope Global -Force

# see https://ohmyposh.dev/docs/installation/prompt
eval "$(oh-my-posh init zsh)"
# eval "$(oh-my-posh init zsh --config /opt/tools/oh-my-posh/etc/wvh.omp.json)"

